<a href="https://colab.research.google.com/github/galindojimenezjuanandres-alt/programacion-1/blob/main/Quiz5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Escritura de archivos en python**

**python permite cargar y crear objtos de archivos dados y tambien permite crear archivos y editar archivos dados**

In [7]:
# crear y escribir un archivo de texto
with open("archivo.txt", 'w') as f:
     f.write("hola, este es un archivo de texto. \n")
     f.write("segunda linea. \n")
     f.write("esto es una prueba. \n")

**Con el argumento "w" se crea el archivo si no existe. tambien sobrescribe el archivo si ya existe, borrando su contenido previo**

Con archivos.txt

(se tiene que tener en cuenta la fomra de separar espacios ya sea cib  , ; .) y se establece  para todo el archivo

In [8]:
with open("archivo.txt", "r") as f:
 print(f.read())

hola, este es un archivo de texto.
segunda linea.
esto es una prueba.

**Con el argumento "r" se leen archivos**

In [9]:
from google.colab import files
files.download("archivo.txt")

In [10]:
# Abrir en modo append para editar un archivo ya exsitente
with open("archivo.txt", "a") as f:
  f.write("\n esta es una nueva linea")
# el \n es una linea vacia

**Con el argumento "a" se sobre escribe el que ya teniamos**

In [26]:
with open("archivo.txt", "r") as f:
 print(f.read())

hola, este es un archivo de texto.
segunda linea.
esto es una prueba.

 esta es una nueva linea
 un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?

In [45]:
with open("archivo.txt", "a") as f:
  f.write("\n  otro ejemplo nuevo ? ")

In [46]:
with open("archivo.txt","r") as f:
  print(f.read())

hola, este es un archivo de texto.
segunda linea.
esto es una prueba.

 esta es una nueva linea
 un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
 esto se repite :o
 esto se repite :o
 esto se repite :o
 esto se repite :o
 esto se repite :o
  a ver
  a ver
  otro ejemplo nuevo ?

In [37]:
with open("archivo.txt", "a") as f:
   f.write("\n esto se repite :o")

In [47]:
with open("archivo.txt","r") as f:
  print(f.read())

hola, este es un archivo de texto.
segunda linea.
esto es una prueba.

 esta es una nueva linea
 un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
 esto se repite :o
 esto se repite :o
 esto se repite :o
 esto se repite :o
 esto se repite :o
  a ver
  a ver
  otro ejemplo nuevo ?

In [39]:
from google.colab import files
files.download("archivo.txt")

**Importar archivos directamente**

In [48]:
from google.colab import files
uploaded = files.upload()

Saving archivo (1).txt to archivo (1).txt

In [52]:
with open("archivo (1).txt", "r") as f:
  print(f.read())

hola, este es un archivo de texto.
segunda linea.
esto es una prueba.

 esta es una nueva linea
 un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
  un nuevo ejemplo ?
 esto se repite :o
 esto se repite :o
 esto se repite :o
 esto se repite :o
 esto se repite :o

In [58]:
with open("archivo (1).txt", "w") as f:
  f.write("\n prueba 2 ")
  f.write("\n prueba 3 ")

In [59]:
with open("archivo (1).txt", "r") as f:
  print(f.read())

 prueba 2
 prueba 3

In [60]:
from google.colab import files
files.download("archivo (1).txt")

**Con archivos .csv**

In [65]:
import csv
datos = [
    ["nombre", "edad ","ciudad"],
    ["juan", 18 , "bucaramga"],
    ["ana", 25 , "medellin"],
    ["laura", 17 , "bucaramanga"]
]
with open("datos.csv", "w", newline="") as x:
  writer = csv.writer(x)
  writer.writerows(datos)

In [67]:
with open("datos.csv", "r") as f :
 print(f.read())

nombre,edad ,ciudad
juan,18,bucaramga
ana,25,medellin
laura,17,bucaramanga

In [68]:
files.download("datos.csv")

In [70]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [71]:
ruta = "/content/drive/MyDrive/datos.csv"
import shutil
shutil.copy("datos.csv", ruta )

'/content/drive/MyDrive/datos.csv'

In [73]:
with open(ruta,"r") as f:
  print(f.read())

nombre,edad ,ciudad
juan,18,bucaramga
ana,25,medellin
laura,17,bucaramanga

In [75]:
with open(ruta, "r") as f:
  data = list(csv.reader(f))

  # Agregar nueva lista
  data.append(["diego",28,"rusia"])
  data

In [76]:
data

[['nombre', 'edad ', 'ciudad'],
 ['juan', '18', 'bucaramga'],
 ['ana', '25', 'medellin'],
 ['laura', '17', 'bucaramanga'],
 ['diego', 28, 'rusia']]

In [78]:
import pandas as pd
data1 = pd.DataFrame(data)
data1

        0      1            2
0  nombre  edad        ciudad
1    juan     18    bucaramga
2     ana     25     medellin
3   laura     17  bucaramanga
4   diego     28        rusia

In [82]:
df = pd.read_csv(ruta)
df

  nombre  edad        ciudad
0   juan     18    bucaramga
1    ana     25     medellin
2  laura     17  bucaramanga
3  Diego     28      Armenia

In [83]:
df["Nueva_columna"] = "valor"
df["Nueva_columna"] = [10, 20, 30, None]
df

  nombre  edad        ciudad  Nueva_columna
0   juan     18    bucaramga           10.0
1    ana     25     medellin           20.0
2  laura     17  bucaramanga           30.0
3  Diego     28      Armenia            NaN

In [79]:
import csv

ruta = "/content/drive/MyDrive/datos.csv"

# Leer
with open(ruta, "r") as f:
    data = list(csv.reader(f))

# Mostrar antes
print("ANTES:")
print(data)

# Agregar fila
data.append(["Diego", "28", "Armenia"])

# Guardar
with open(ruta, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

# Mostrar después
print("\nDESPUÉS:")
with open(ruta, "r") as f:
    print(f.read())

ANTES:
[['nombre', 'edad ', 'ciudad'], ['juan', '18', 'bucaramga'], ['ana', '25', 'medellin'], ['laura', '17', 'bucaramanga']]

DESPUÉS:
nombre,edad ,ciudad
juan,18,bucaramga
ana,25,medellin
laura,17,bucaramanga
Diego,28,Armenia

In [80]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks',
 'a60fc6ee3229bbeb5340419d06ed354b.png',
 'bitacora 9 juan andres galindo jimenez .xlsx',
 'GFPI-F-147V4 BITACORA 9 JCM (1).xlsx',
 'WhatsApp Image 2025-10-06 at 10.35.56 PM.jpeg',
 'cedula.pdf',
 'juan andres galindo jimenez.pdf',
 'GALINDO JIMENEZ JUAN ANDRES.pdf',
 '..gdoc',
 'Juan Andres.jpg',
 'liquidacionPregradoPresencial_copia (2).pdf',
 'Liquidación ',
 'liquidacionPregradoPresencial_copia (1).pdf',
 'liquidacionPregradoPresencial_copia.pdf',
 'Saber leer_INSTITUTO CERVANTES.gdoc',
 'datos.csv']